# Generated by Django 3.1.3 on 2020-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='<django.db.models.fields.CharField>',
        ),
        migrations.AddField(
            model_name='voter',
            name='bukti_foto',
            field=models.ImageField(default='something.png', upload_to=''),
            preserve_default=False,
        ),
    ]
