# Generated by Django 3.1.3 on 2020-11-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201110_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
