# Generated by Django 3.1.3 on 2020-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
