# Generated by Django 3.1.3 on 2020-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201114_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='angkatan',
            field=models.CharField(choices=[('S1 2020', 'S1 2020'), ('S1 2019', 'S1 2019'), ('S1 2018', 'S1 2018'), ('S2', 'S2'), ('S3', 'S3')], max_length=50),
        ),
    ]
