# Generated by Django 3.1.3 on 2020-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201120_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='prodi',
            field=models.CharField(choices=[('Profesi Apoteker', 'Profesi Apoteker'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='angkatan',
            field=models.CharField(choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('92', '92')], max_length=50),
        ),
    ]
