# Generated by Django 3.1.3 on 2020-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201122_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='bukti_foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
