# Generated by Django 3.1.3 on 2020-11-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201122_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='prodi',
        ),
    ]
