# Generated by Django 3.1.3 on 2020-11-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_voter_prodi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='angkatan',
        ),
        migrations.AddField(
            model_name='voter',
            name='prodi',
            field=models.CharField(default='S1 - Angkatan 2019', max_length=50),
            preserve_default=False,
        ),
    ]
