# Generated by Django 3.1.3 on 2020-11-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201123_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='prodi',
            field=models.CharField(choices=[('S1 - Angkatan 2014', 'S1 - Angkatan 2014'), ('S1 - Angkatan 2015', 'S1 - Angkatan 2015'), ('S1 - Angkatan 2016', 'S1 - Angkatan 2016'), ('S1 - Angkatan 2017', 'S1 - Angkatan 2017'), ('S1 - Angkatan 2018', 'S1 - Angkatan 2018'), ('S1 - Angkatan 2019', 'S1 - Angkatan 2019'), ('S1 - Angkatan 2020', 'S1 - Angkatan 2020'), ('S2', 'S2'), ('S3', 'S3'), ('Profesi Apoteker', 'Profesi Apoteker')], max_length=50),
        ),
    ]
