# Generated by Django 3.1.3 on 2020-11-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201110_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bem_vote',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='bpm_vote',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
