# Generated by Django 3.1.3 on 2020-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20201117_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bem_vote',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='bpm_vote',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
